const List<Map<String, dynamic>> attendanceListSamples = [
  {
    "id": 1,
    "activity": "Check In",
    "date": "16 Desember 2024",
    "time": "07:54 am",
    "status": "Tepat Waktu",
    "check_in_status": "Sehat",
    "check_out_status": "Happy",
    "detail_activity": "Check In tanggal 16 Desember 2024 pukul 07:54 am",
  },
  {
    "id": 2,
    "activity": "Check Out",
    "date": "16 Desember 2024",
    "time": "06:16 pm",
    "status": "Tepat Waktu",
    "check_in_status": "Sehat",
    "check_out_status": "Happy",
    "detail_activity": "Check Out tanggal 16 Desember 2024 pukul 06:16 pm",
  },
  {
    "id": 3,
    "activity": "Check In",
    "date": "17 Desember 2024",
    "time": "06:16 am",
    "status": "Tepat Waktu",
    "check_in_status": "Sehat",
    "check_out_status": "Happy",
    "detail_activity": "Check In tanggal 17 Desember 2024 pukul 06:16 am",
  },
  {
    "id": 4,
    "activity": "Check Out",
    "date": "17 Desember 2024",
    "time": "06:02 pm",
    "status": "Tepat Waktu",
    "check_in_status": "Sehat",
    "check_out_status": "Happy",
    "detail_activity": "Check Out tanggal 17 Desember 2024 pukul 06:02 pm",
  },
  {
    "id": 5,
    "activity": "Check In",
    "date": "18 Desember 2024",
    "time": "10:22 am",
    "status": "Tepat Waktu",
    "check_in_status": "Sehat",
    "check_out_status": "Happy",
    "detail_activity": "Check In tanggal 18 Desember 2024 pukul 10:22 am",
  },
  {
    "id": 6,
    "activity": "Check Out",
    "date": "18 Desember 2024",
    "time": "05:22 pm",
    "status": "Tepat Waktu",
    "check_in_status": "Sehat",
    "check_out_status": "Happy",
    "detail_activity": "Check Out tanggal 18 Desember 2024 pukul 05:22 pm",
  },
];
