name: dpp_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  flutter_swipe_button: ^2.1.3
  flutter_dotenv: ^5.2.1
  go_router: ^14.3.0
  iconsax: ^0.0.8
  intl: ^0.20.1
  odoo_rpc: ^0.5.8
  path: ^1.9.0
  permission_handler: ^11.3.1
  rename: ^3.0.2
  timezone: ^0.10.0
  odoo_repository: ^0.5.9
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  json_serializable: ^6.9.2
  json_annotation: ^4.9.0
  geolocator: ^13.0.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  camera: ^0.11.0+2
  url_launcher: ^6.3.1
  http: ^1.3.0
  flutter_datetime_picker_plus: ^2.2.0
  translator: ^1.0.3+1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/videos/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-ExtraBold.ttf
        - asset: assets/fonts/Lexend-Bold.ttf
        - asset: assets/fonts/Lexend-SemiBold.ttf
        - asset: assets/fonts/Lexend-Medium.ttf
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-Thin.ttf
        - asset: assets/fonts/Lexend-Light.ttf
        - asset: assets/fonts/Lexend-ExtraLight.ttf
